/// <reference types="next" />
/// <reference types="next/image-types/global" />

// Permanent, committed twin of the auto-generated next-env.d.ts.
// Required because CI runs `tsc --noEmit` before `next build`, so the
// auto-generated file isn't present yet. Declaring the same triple-slash
// references here ensures asset imports (jpg/png/svg as modules) type-check
// from a fresh checkout without depending on Next having run first.
//
// next-env.d.ts is still gitignored and gets regenerated by next dev/build;
// it's harmless to have both.
